### PR TITLE
motodisk: Add --port and --baud commandline options

### PR DESCRIPTION
**Pull request by jonnor**
Port especially is useful to be able to configure,
since differs between operating systems and connection method
(etc USB versus non-USB).

### CODE REVIEW

**Comment by jonnor** [comment]
@treeherder ping, any response to this?

**Comment by treeherder** [comment]
sorry i've been traveling and moving and stuff, i'll look at it!

**Comment by JensDyvik** [comment]
We are supergrateful for your script sharing. It helped us a lot to get our 19 year old motoman sk6 working. After configuring the com port, the motodisk script has been working bug less to transfer files for almost a year. We are currently testing cnc milling and 3d printing by robot in our fab lab

**Comment by jonnor** [comment]
Thanks for the merge! Here is one video of what we've been up to: https://www.youtube.com/watch?v=GnwZuvjI4-o

**Comment by treeherder** [comment]
That's fantastic! I know it's an open source project, but I honestly never
believed somebody else would use it outside of our space in Oakland. Where
are you located?

**Comment by jonnor** [comment]
We're in Oslo, Norway. http://fellesverkstedet.no/#updates

**Pull request merged**
